### ISSUE TITLE
java.lang.NoSuchMethodError 

### ISSUE THREAD

**Issue by wipatrick** [smueller18/avro-builder#4]
I get the following error when schema is to be build.

```sh
ava.lang.NoSuchMethodError: org.apache.avro.Schema.setLogicalType(Lorg/apache/avro/LogicalType;)V
	at org.apache.avro.LogicalType.addToSchema(LogicalType.java:72)
	at com.github.smueller18.avro.builder.AvroBuilder.buildSchema(AvroBuilder.java:174)
	at com.github.smueller18.avro.builder.AvroBuilder.<init>(AvroBuilder.java:29)
...
```

line 174 in ```AvroBuilder``` referes to timestamp field:
```java
case TIMESTAMP_MILLIS:
    Schema timestampMillisType = LogicalTypes.timestampMillis().addToSchema(Schema.create(Schema.Type.LONG));
    fieldBuilder.type(timestampMillisType).noDefault();
    break;
```

any ideas?

**Comment by smueller18** [comment]
which avro version are you using?

**Comment by wipatrick** [comment]
1.8.1 the same as you

**Comment by smueller18** [comment]
probably because intellij does not support latest junit.jupiter. Changed to version 5.0.0-M4 242c836911c63e221be9eb8e6454cd4033581cb0

**Comment by wipatrick** [comment]
it works from idea spinning up local mini-flink instance in the JVM, but the error occurs when packaging the jar and deploying it to a Flink cluster. Flink relies on Avro 1.7.7. However, I explicitly tell not to use that version inside the project's ```pom.xml```. 

```xml
<build>
  <plugins>
    <!-- We use the maven-shade plugin to create a fat jar that contains all dependencies
    except flink and it's transitive dependencies. The resulting fat-jar can be executed
    on a cluster. Change the value of Program-Class if your program entry point changes. -->
    <plugin>
      <groupId>org.apache.maven.plugins</groupId>
      <artifactId>maven-shade-plugin</artifactId>
      <version>2.4.1</version>
      <executions>
        <!-- Run shade goal on package phase -->
        <execution>
          <phase>package</phase>
          <goals>
            <goal>shade</goal>
          </goals>
          <configuration>
            <artifactSet>
              <excludes>
                <!-- This list contains all dependencies of flink-dist
                Everything else will be packaged into the fat-jar
                -->
                <exclude>org.apache.flink:flink-annotations</exclude>
                <exclude>org.apache.flink:flink-shaded-hadoop2</exclude>
                <exclude>org.apache.flink:flink-shaded-curator-recipes</exclude>
                <exclude>org.apache.flink:flink-core</exclude>
                <exclude>org.apache.flink:flink-java</exclude>
                <exclude>org.apache.flink:flink-scala_2.10</exclude>
                <exclude>org.apache.flink:flink-runtime_2.10</exclude>
                <exclude>org.apache.flink:flink-optimizer_2.10</exclude>
                <exclude>org.apache.flink:flink-clients_2.10</exclude>
                <exclude>org.apache.flink:flink-avro_2.10</exclude>
                <exclude>org.apache.flink:flink-examples-batch_2.10</exclude>
                <exclude>org.apache.flink:flink-examples-streaming_2.10</exclude>
                <exclude>org.apache.flink:flink-streaming-java_2.10</exclude>
                <exclude>org.apache.flink:flink-streaming-scala_2.10</exclude>
                <exclude>org.apache.flink:flink-scala-shell_2.10</exclude>
                <exclude>org.apache.flink:flink-python</exclude>
                <exclude>org.apache.flink:flink-metrics-core</exclude>
                <exclude>org.apache.flink:flink-metrics-jmx</exclude>
                <exclude>org.apache.flink:flink-statebackend-rocksdb_2.10</exclude>

                <!-- Also exclude very big transitive dependencies of Flink

                WARNING: You have to remove these excludes if your code relies on other
                versions of these dependencies.

                -->

                <exclude>log4j:log4j</exclude>
                <exclude>org.scala-lang:scala-library</exclude>
                <exclude>org.scala-lang:scala-compiler</exclude>
                <exclude>org.scala-lang:scala-reflect</exclude>
                <exclude>com.data-artisans:flakka-actor_*</exclude>
                <exclude>com.data-artisans:flakka-remote_*</exclude>
                <exclude>com.data-artisans:flakka-slf4j_*</exclude>
                <exclude>io.netty:netty-all</exclude>
                <exclude>io.netty:netty</exclude>
                <exclude>commons-fileupload:commons-fileupload</exclude>
                <!--<exclude>org.apache.avro:avro</exclude>-->
...
```

**Comment by smueller18** [comment]
avro version 1.7.7 does not support logical types, thats the reason why I asked for the version before
